load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

string_flag(
    name = "standard",
    build_setting_default = "2019",
    values = ["1993", "2000", "2002", "2008", "2019"],
    visibility = ["//visibility:public"],
)

[
    config_setting(
        name = "standard_%s" % standard,
        flag_values = {":standard": standard},
        visibility = ["//visibility:public"],
    )
    for standard in ["1993", "2000", "2002", "2008", "2019"]
]
